### ISSUE TITLE
Dataset links live?

### ISSUE THREAD

**Issue by suzanne-stathatos** [f-ilic/AppearanceFreeActionRecognition#3]
Hi! I'm interested in exploring this dataset. Are the `wget` links still live? I get a `Connection refused` error when I try to retrieve the zip files.

**Comment by f-ilic** [comment]
Hi, there seems to have been an internal issue with our filehosting.
Its resolved now;
You should be able to download it  
```
wget https://files.icg.tugraz.at/f/9b501254b9b0499cbec9/?dl=1 -O afd101.zip
```
or from the alternative hosting site: https://cloud.tugraz.at/index.php/s/BMfNRLPLsXs5qsM

Please let me know if there are other hickups. In that case i'll host it on google drive or something similar.

**Comment by suzanne-stathatos** [comment]
Amazing - the links now work. Thank you for the quick reply!

**Comment by lolotta** [comment]
Hi, the link does not work for me either
